package com.hywa.bigdata.storage.entity;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class SysUser {

    private String GUID;

    private String CNAME;

    private String CCODE;

    private String CSTATUS;

    private String CREATEUSER;

    private Date CREATEDATE;

    private String UPDATEUSER;

    private Date UPDATEDATE;

    private String CVER;

    private String REAL_NAME;

    private String PASSWORD;

    private String PHOTO;

    private Integer SEX;

    private String REF_SYS_DEPARTMENT;

    private String REF_PJ;

    private String REF_ZHCC_S_ROLE;

    private String PHONE;

    private String WEIXIN;

    private String QQ;

    private String EMAIL;

    private String ID_CARD;

    private Date BIRTHDAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.HEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private Integer HEIGHT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.WEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private Float WEIGHT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NATIVE_PLACE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private String NATIVE_PLACE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NATION
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private Integer NATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CURR_ADDRESS
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private String CURR_ADDRESS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_IP
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private String LOGIN_IP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_DATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private Date LOGIN_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_COUNT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private Long LOGIN_COUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ORG_ID
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    private String ORG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.GUID
     *
     * @return the value of sys_user.GUID
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    @JSONField(name = "id")
    public String getGUID() {
        return GUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.GUID
     *
     * @param GUID the value for sys_user.GUID
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setGUID(String GUID) {
        this.GUID = GUID == null ? null : GUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CNAME
     *
     * @return the value of sys_user.CNAME
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCNAME() {
        return CNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CNAME
     *
     * @param CNAME the value for sys_user.CNAME
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCNAME(String CNAME) {
        this.CNAME = CNAME == null ? null : CNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CCODE
     *
     * @return the value of sys_user.CCODE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCCODE() {
        return CCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CCODE
     *
     * @param CCODE the value for sys_user.CCODE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCCODE(String CCODE) {
        this.CCODE = CCODE == null ? null : CCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CSTATUS
     *
     * @return the value of sys_user.CSTATUS
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCSTATUS() {
        return CSTATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CSTATUS
     *
     * @param CSTATUS the value for sys_user.CSTATUS
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCSTATUS(String CSTATUS) {
        this.CSTATUS = CSTATUS == null ? null : CSTATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATEUSER
     *
     * @return the value of sys_user.CREATEUSER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCREATEUSER() {
        return CREATEUSER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATEUSER
     *
     * @param CREATEUSER the value for sys_user.CREATEUSER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCREATEUSER(String CREATEUSER) {
        this.CREATEUSER = CREATEUSER == null ? null : CREATEUSER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATEDATE
     *
     * @return the value of sys_user.CREATEDATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Date getCREATEDATE() {
        return CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATEDATE
     *
     * @param CREATEDATE the value for sys_user.CREATEDATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCREATEDATE(Date CREATEDATE) {
        this.CREATEDATE = CREATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATEUSER
     *
     * @return the value of sys_user.UPDATEUSER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getUPDATEUSER() {
        return UPDATEUSER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATEUSER
     *
     * @param UPDATEUSER the value for sys_user.UPDATEUSER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setUPDATEUSER(String UPDATEUSER) {
        this.UPDATEUSER = UPDATEUSER == null ? null : UPDATEUSER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATEDATE
     *
     * @return the value of sys_user.UPDATEDATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Date getUPDATEDATE() {
        return UPDATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATEDATE
     *
     * @param UPDATEDATE the value for sys_user.UPDATEDATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setUPDATEDATE(Date UPDATEDATE) {
        this.UPDATEDATE = UPDATEDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CVER
     *
     * @return the value of sys_user.CVER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCVER() {
        return CVER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CVER
     *
     * @param CVER the value for sys_user.CVER
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCVER(String CVER) {
        this.CVER = CVER == null ? null : CVER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REAL_NAME
     *
     * @return the value of sys_user.REAL_NAME
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    @JSONField(name = "name")
    public String getREAL_NAME() {
        return REAL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REAL_NAME
     *
     * @param REAL_NAME the value for sys_user.REAL_NAME
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setREAL_NAME(String REAL_NAME) {
        this.REAL_NAME = REAL_NAME == null ? null : REAL_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PASSWORD
     *
     * @return the value of sys_user.PASSWORD
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PASSWORD
     *
     * @param PASSWORD the value for sys_user.PASSWORD
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHOTO
     *
     * @return the value of sys_user.PHOTO
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getPHOTO() {
        return PHOTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHOTO
     *
     * @param PHOTO the value for sys_user.PHOTO
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setPHOTO(String PHOTO) {
        this.PHOTO = PHOTO == null ? null : PHOTO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SEX
     *
     * @return the value of sys_user.SEX
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Integer getSEX() {
        return SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SEX
     *
     * @param SEX the value for sys_user.SEX
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setSEX(Integer SEX) {
        this.SEX = SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REF_SYS_DEPARTMENT
     *
     * @return the value of sys_user.REF_SYS_DEPARTMENT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getREF_SYS_DEPARTMENT() {
        return REF_SYS_DEPARTMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REF_SYS_DEPARTMENT
     *
     * @param REF_SYS_DEPARTMENT the value for sys_user.REF_SYS_DEPARTMENT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setREF_SYS_DEPARTMENT(String REF_SYS_DEPARTMENT) {
        this.REF_SYS_DEPARTMENT = REF_SYS_DEPARTMENT == null ? null : REF_SYS_DEPARTMENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REF_PJ
     *
     * @return the value of sys_user.REF_PJ
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getREF_PJ() {
        return REF_PJ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REF_PJ
     *
     * @param REF_PJ the value for sys_user.REF_PJ
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setREF_PJ(String REF_PJ) {
        this.REF_PJ = REF_PJ == null ? null : REF_PJ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REF_ZHCC_S_ROLE
     *
     * @return the value of sys_user.REF_ZHCC_S_ROLE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getREF_ZHCC_S_ROLE() {
        return REF_ZHCC_S_ROLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REF_ZHCC_S_ROLE
     *
     * @param REF_ZHCC_S_ROLE the value for sys_user.REF_ZHCC_S_ROLE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setREF_ZHCC_S_ROLE(String REF_ZHCC_S_ROLE) {
        this.REF_ZHCC_S_ROLE = REF_ZHCC_S_ROLE == null ? null : REF_ZHCC_S_ROLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    @JSONField(name = "phone")
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param PHONE the value for sys_user.PHONE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WEIXIN
     *
     * @return the value of sys_user.WEIXIN
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getWEIXIN() {
        return WEIXIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WEIXIN
     *
     * @param WEIXIN the value for sys_user.WEIXIN
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setWEIXIN(String WEIXIN) {
        this.WEIXIN = WEIXIN == null ? null : WEIXIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.QQ
     *
     * @return the value of sys_user.QQ
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getQQ() {
        return QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.QQ
     *
     * @param QQ the value for sys_user.QQ
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setQQ(String QQ) {
        this.QQ = QQ == null ? null : QQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param EMAIL the value for sys_user.EMAIL
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID_CARD
     *
     * @return the value of sys_user.ID_CARD
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getID_CARD() {
        return ID_CARD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID_CARD
     *
     * @param ID_CARD the value for sys_user.ID_CARD
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setID_CARD(String ID_CARD) {
        this.ID_CARD = ID_CARD == null ? null : ID_CARD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.BIRTHDAY
     *
     * @return the value of sys_user.BIRTHDAY
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Date getBIRTHDAY() {
        return BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.BIRTHDAY
     *
     * @param BIRTHDAY the value for sys_user.BIRTHDAY
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setBIRTHDAY(Date BIRTHDAY) {
        this.BIRTHDAY = BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.HEIGHT
     *
     * @return the value of sys_user.HEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Integer getHEIGHT() {
        return HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.HEIGHT
     *
     * @param HEIGHT the value for sys_user.HEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setHEIGHT(Integer HEIGHT) {
        this.HEIGHT = HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.WEIGHT
     *
     * @return the value of sys_user.WEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Float getWEIGHT() {
        return WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.WEIGHT
     *
     * @param WEIGHT the value for sys_user.WEIGHT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setWEIGHT(Float WEIGHT) {
        this.WEIGHT = WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NATIVE_PLACE
     *
     * @return the value of sys_user.NATIVE_PLACE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getNATIVE_PLACE() {
        return NATIVE_PLACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NATIVE_PLACE
     *
     * @param NATIVE_PLACE the value for sys_user.NATIVE_PLACE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setNATIVE_PLACE(String NATIVE_PLACE) {
        this.NATIVE_PLACE = NATIVE_PLACE == null ? null : NATIVE_PLACE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NATION
     *
     * @return the value of sys_user.NATION
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Integer getNATION() {
        return NATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NATION
     *
     * @param NATION the value for sys_user.NATION
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setNATION(Integer NATION) {
        this.NATION = NATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CURR_ADDRESS
     *
     * @return the value of sys_user.CURR_ADDRESS
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getCURR_ADDRESS() {
        return CURR_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CURR_ADDRESS
     *
     * @param CURR_ADDRESS the value for sys_user.CURR_ADDRESS
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setCURR_ADDRESS(String CURR_ADDRESS) {
        this.CURR_ADDRESS = CURR_ADDRESS == null ? null : CURR_ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_IP
     *
     * @return the value of sys_user.LOGIN_IP
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getLOGIN_IP() {
        return LOGIN_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_IP
     *
     * @param LOGIN_IP the value for sys_user.LOGIN_IP
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setLOGIN_IP(String LOGIN_IP) {
        this.LOGIN_IP = LOGIN_IP == null ? null : LOGIN_IP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_DATE
     *
     * @return the value of sys_user.LOGIN_DATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Date getLOGIN_DATE() {
        return LOGIN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_DATE
     *
     * @param LOGIN_DATE the value for sys_user.LOGIN_DATE
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setLOGIN_DATE(Date LOGIN_DATE) {
        this.LOGIN_DATE = LOGIN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_COUNT
     *
     * @return the value of sys_user.LOGIN_COUNT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public Long getLOGIN_COUNT() {
        return LOGIN_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_COUNT
     *
     * @param LOGIN_COUNT the value for sys_user.LOGIN_COUNT
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setLOGIN_COUNT(Long LOGIN_COUNT) {
        this.LOGIN_COUNT = LOGIN_COUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ORG_ID
     *
     * @return the value of sys_user.ORG_ID
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public String getORG_ID() {
        return ORG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ORG_ID
     *
     * @param ORG_ID the value for sys_user.ORG_ID
     *
     * @mbggenerated Mon Jun 04 17:08:49 CST 2018
     */
    public void setORG_ID(String ORG_ID) {
        this.ORG_ID = ORG_ID == null ? null : ORG_ID.trim();
    }
}